// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/importErrors": {
            "get": {
                "description": "Get the importErrors.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "[Workflow]"
                ],
                "summary": "Get importErrors",
                "operationId": "get-import-errors",
                "responses": {
                    "200": {
                        "description": "Successfully get the importErrors.",
                        "schema": {
                            "$ref": "#/definitions/model.ImportErrorCollection"
                        }
                    },
                    "400": {
                        "description": "Sent bad request.",
                        "schema": {
                            "$ref": "#/definitions/common.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Failed to get the importErrors.",
                        "schema": {
                            "$ref": "#/definitions/common.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/readyz": {
            "get": {
                "description": "Check Cicada is ready",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "[Admin]\tSystem management"
                ],
                "summary": "Check Ready",
                "operationId": "health-check-readyz",
                "responses": {
                    "200": {
                        "description": "Successfully get ready state.",
                        "schema": {
                            "$ref": "#/definitions/model.SimpleMsg"
                        }
                    },
                    "500": {
                        "description": "Failed to check ready state.",
                        "schema": {
                            "$ref": "#/definitions/common.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/run_script": {
            "post": {
                "description": "Run script on target with NS ID, MCI ID and VM ID.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "[Cicada Task Component]"
                ],
                "summary": "Run script on target",
                "operationId": "run-script",
                "parameters": [
                    {
                        "description": "Workflow content",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.RunScriptReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Result of the script running",
                        "schema": {
                            "$ref": "#/definitions/model.ScriptResult"
                        }
                    },
                    "400": {
                        "description": "Sent bad request.",
                        "schema": {
                            "$ref": "#/definitions/common.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Failed to run script",
                        "schema": {
                            "$ref": "#/definitions/common.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/sleep_time": {
            "post": {
                "description": "Runs sleep command on cicada and waits for configured time. Wait for 10 seconds if time value is not provided.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "[Cicada Task Component]"
                ],
                "summary": "Run sleep command on cicada",
                "operationId": "sleep-time",
                "parameters": [
                    {
                        "description": "SleepTime request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.SleepTimeReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Result of sleep",
                        "schema": {
                            "$ref": "#/definitions/model.ScriptResult"
                        }
                    },
                    "400": {
                        "description": "Sent bad request.",
                        "schema": {
                            "$ref": "#/definitions/common.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Failed to run script",
                        "schema": {
                            "$ref": "#/definitions/common.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/task/{taskId}": {
            "get": {
                "description": "Get the task directly.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "[Workflow]"
                ],
                "summary": "Get Task Directly",
                "operationId": "get-task-directly",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID of the task.",
                        "name": "taskId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully get the task.",
                        "schema": {
                            "$ref": "#/definitions/model.Task"
                        }
                    },
                    "400": {
                        "description": "Sent bad request.",
                        "schema": {
                            "$ref": "#/definitions/common.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Failed to get the task.",
                        "schema": {
                            "$ref": "#/definitions/common.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/task_component": {
            "get": {
                "description": "Get a list of task component.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "[Task Component]"
                ],
                "summary": "List TaskComponent",
                "operationId": "list-task-component",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Page of the task component list.",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Row of the task component list.",
                        "name": "row",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully get a list of task component.",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/domain.TaskComponent"
                            }
                        }
                    },
                    "400": {
                        "description": "Sent bad request.",
                        "schema": {
                            "$ref": "#/definitions/common.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Failed to get a list of task component.",
                        "schema": {
                            "$ref": "#/definitions/common.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Register the task component.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "[Task Component]"
                ],
                "summary": "Create TaskComponent",
                "operationId": "create-task-component",
                "parameters": [
                    {
                        "description": "task component to create.",
                        "name": "TaskComponent",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.CreateTaskComponentReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully register the task component",
                        "schema": {
                            "$ref": "#/definitions/domain.TaskComponent"
                        }
                    },
                    "400": {
                        "description": "Sent bad request.",
                        "schema": {
                            "$ref": "#/definitions/common.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Failed to register the task component",
                        "schema": {
                            "$ref": "#/definitions/common.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/task_component/name/{tcName}": {
            "get": {
                "description": "Get the task component by name.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "[Task Component]"
                ],
                "summary": "Get TaskComponent by Name",
                "operationId": "get-task-component-by-name",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Name of the TaskComponent",
                        "name": "tcName",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully get the task component",
                        "schema": {
                            "$ref": "#/definitions/domain.TaskComponent"
                        }
                    },
                    "400": {
                        "description": "Sent bad request.",
                        "schema": {
                            "$ref": "#/definitions/common.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Failed to get the task component",
                        "schema": {
                            "$ref": "#/definitions/common.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/task_component/{tcId}": {
            "get": {
                "description": "Get the task component.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "[Task Component]"
                ],
                "summary": "Get TaskComponent",
                "operationId": "get-task-component",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID of the TaskComponent",
                        "name": "tcId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully get the task component",
                        "schema": {
                            "$ref": "#/definitions/domain.TaskComponent"
                        }
                    },
                    "400": {
                        "description": "Sent bad request.",
                        "schema": {
                            "$ref": "#/definitions/common.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Failed to get the task component",
                        "schema": {
                            "$ref": "#/definitions/common.ErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "description": "Update the task component.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "[Task Component]"
                ],
                "summary": "Update TaskComponent",
                "operationId": "update-task-component",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID of the TaskComponent",
                        "name": "tcId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "task component to modify.",
                        "name": "TaskComponent",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.CreateTaskComponentReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully update the task component",
                        "schema": {
                            "$ref": "#/definitions/domain.TaskComponent"
                        }
                    },
                    "400": {
                        "description": "Sent bad request.",
                        "schema": {
                            "$ref": "#/definitions/common.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Failed to update the task component",
                        "schema": {
                            "$ref": "#/definitions/common.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete the task component.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "[Task Component]"
                ],
                "summary": "Delete TaskComponent",
                "operationId": "delete-task-component",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID of the task component.",
                        "name": "tcId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully delete the task component",
                        "schema": {
                            "$ref": "#/definitions/model.SimpleMsg"
                        }
                    },
                    "400": {
                        "description": "Sent bad request.",
                        "schema": {
                            "$ref": "#/definitions/common.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Failed to delete the task component",
                        "schema": {
                            "$ref": "#/definitions/common.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/workflow": {
            "get": {
                "description": "Get a workflow list.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "[Workflow]"
                ],
                "summary": "List Workflow",
                "operationId": "list-workflow",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Name of the workflow",
                        "name": "name",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Page of the workflow list.",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Row of the workflow list.",
                        "name": "row",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully get a workflow list.",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.Workflow"
                            }
                        }
                    },
                    "400": {
                        "description": "Sent bad request.",
                        "schema": {
                            "$ref": "#/definitions/common.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Failed to get a workflow list.",
                        "schema": {
                            "$ref": "#/definitions/common.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Create a workflow.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "[Workflow]"
                ],
                "summary": "Create Workflow",
                "operationId": "create-workflow",
                "parameters": [
                    {
                        "description": "Workflow content",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.CreateWorkflowReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully create the workflow.",
                        "schema": {
                            "$ref": "#/definitions/model.WorkflowTemplate"
                        }
                    },
                    "400": {
                        "description": "Sent bad request.",
                        "schema": {
                            "$ref": "#/definitions/common.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Failed to create workflow.",
                        "schema": {
                            "$ref": "#/definitions/common.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/workflow/name/{wfName}": {
            "get": {
                "description": "Get the workflow by name.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "[Workflow]"
                ],
                "summary": "Get Workflow by Name",
                "operationId": "get-workflow-by-name",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Name of the workflow.",
                        "name": "wfName",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully get the workflow.",
                        "schema": {
                            "$ref": "#/definitions/model.Workflow"
                        }
                    },
                    "400": {
                        "description": "Sent bad request.",
                        "schema": {
                            "$ref": "#/definitions/common.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Failed to get the workflow.",
                        "schema": {
                            "$ref": "#/definitions/common.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/workflow/tx": {
            "post": {
                "description": "Create a workflow with TaskGroups/Tasks in a single DB transaction.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "[Workflow]"
                ],
                "summary": "Create Workflow (DB Tx)",
                "operationId": "create-workflow-tx",
                "parameters": [
                    {
                        "description": "Workflow content",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.CreateWorkflowReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully create the workflow.",
                        "schema": {
                            "$ref": "#/definitions/model.Workflow"
                        }
                    },
                    "400": {
                        "description": "Sent bad request.",
                        "schema": {
                            "$ref": "#/definitions/common.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Failed to create workflow.",
                        "schema": {
                            "$ref": "#/definitions/common.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/workflow/version/{verId}": {
            "get": {
                "description": "Get the WorkflowVersion.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "[Workflow]"
                ],
                "summary": "Get WorkflowVersion",
                "operationId": "get-WorkflowVersion",
                "parameters": [
                    {
                        "type": "string",
                        "description": "wfId of the workflow",
                        "name": "wfId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "ID of the WorkflowVersion.",
                        "name": "verId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully get the WorkflowVersion.",
                        "schema": {
                            "$ref": "#/definitions/model.WorkflowVersionSwg"
                        }
                    },
                    "400": {
                        "description": "Sent bad request.",
                        "schema": {
                            "$ref": "#/definitions/common.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Failed to get the WorkflowVersion.",
                        "schema": {
                            "$ref": "#/definitions/common.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/workflow/{wfId}": {
            "get": {
                "description": "Get the workflow.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "[Workflow]"
                ],
                "summary": "Get Workflow",
                "operationId": "get-workflow",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID of the workflow.",
                        "name": "wfId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully get the workflow.",
                        "schema": {
                            "$ref": "#/definitions/model.Workflow"
                        }
                    },
                    "400": {
                        "description": "Sent bad request.",
                        "schema": {
                            "$ref": "#/definitions/common.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Failed to get the workflow.",
                        "schema": {
                            "$ref": "#/definitions/common.ErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "description": "Update the workflow content.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "[Workflow]"
                ],
                "summary": "Update Workflow",
                "operationId": "update-workflow",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID of the workflow.",
                        "name": "wfId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Workflow to modify.",
                        "name": "Workflow",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.CreateWorkflowReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully update the workflow",
                        "schema": {
                            "$ref": "#/definitions/model.Workflow"
                        }
                    },
                    "400": {
                        "description": "Sent bad request.",
                        "schema": {
                            "$ref": "#/definitions/common.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Failed to update the workflow",
                        "schema": {
                            "$ref": "#/definitions/common.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete the workflow.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "[Workflow]"
                ],
                "summary": "Delete Workflow",
                "operationId": "delete-workflow",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID of the workflow.",
                        "name": "wfId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully delete the workflow",
                        "schema": {
                            "$ref": "#/definitions/model.SimpleMsg"
                        }
                    },
                    "400": {
                        "description": "Sent bad request.",
                        "schema": {
                            "$ref": "#/definitions/common.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Failed to delete the workflow",
                        "schema": {
                            "$ref": "#/definitions/common.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/workflow/{wfId}/eventlogs": {
            "get": {
                "description": "Get Eventlog.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "[Workflow]"
                ],
                "summary": "Get Eventlog",
                "operationId": "get-event-logs",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID of the workflow.",
                        "name": "wfId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "ID of the workflow run.",
                        "name": "wfRunId",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "ID of the task.",
                        "name": "taskId",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully get the workflow.",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.EventLog"
                            }
                        }
                    },
                    "400": {
                        "description": "Sent bad request.",
                        "schema": {
                            "$ref": "#/definitions/common.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Failed to get the workflow.",
                        "schema": {
                            "$ref": "#/definitions/common.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/workflow/{wfId}/run": {
            "post": {
                "description": "Run the workflow.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "[Workflow]"
                ],
                "summary": "Run Workflow",
                "operationId": "run-workflow",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID of the workflow.",
                        "name": "wfId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully run the workflow.",
                        "schema": {
                            "$ref": "#/definitions/model.SimpleMsg"
                        }
                    },
                    "400": {
                        "description": "Sent bad request.",
                        "schema": {
                            "$ref": "#/definitions/common.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Failed to run the Workflow",
                        "schema": {
                            "$ref": "#/definitions/common.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/workflow/{wfId}/runs": {
            "get": {
                "description": "Get DAG runs from Airflow API.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "[Workflow]"
                ],
                "summary": "Get workflowRuns",
                "operationId": "get-workflow-runs",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID of the workflow.",
                        "name": "wfId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully get the workflowRuns.",
                        "schema": {
                            "$ref": "#/definitions/model.WorkflowRun"
                        }
                    },
                    "400": {
                        "description": "Sent bad request.",
                        "schema": {
                            "$ref": "#/definitions/common.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Failed to get the workflowRuns.",
                        "schema": {
                            "$ref": "#/definitions/common.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Airflow에서 DAG 종료 시 POST로 보낸 workflow run 데이터를 DB에 저장. 실행내역 전부 INSERT.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "[Workflow]"
                ],
                "summary": "Create WorkflowRun (DB 저장)",
                "operationId": "create-workflow-run",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID of the workflow.",
                        "name": "wfId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Workflow run data (Airflow callback payload)",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.CreateWorkflowRunReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully saved workflow run",
                        "schema": {
                            "$ref": "#/definitions/model.WorkflowRun"
                        }
                    },
                    "400": {
                        "description": "Sent bad request.",
                        "schema": {
                            "$ref": "#/definitions/common.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Failed to save workflow run",
                        "schema": {
                            "$ref": "#/definitions/common.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/workflow/{wfId}/status": {
            "get": {
                "description": "Get the WorkflowStatus.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "[Workflow]"
                ],
                "summary": "Get WorkflowStatus",
                "operationId": "get-WorkflowStatus",
                "parameters": [
                    {
                        "type": "string",
                        "description": "wfId of the workflow",
                        "name": "wfId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully get the WorkflowVersion.",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.WorkflowStatus"
                            }
                        }
                    },
                    "400": {
                        "description": "Sent bad request.",
                        "schema": {
                            "$ref": "#/definitions/common.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Failed to get the WorkflowVersion.",
                        "schema": {
                            "$ref": "#/definitions/common.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/workflow/{wfId}/task": {
            "get": {
                "description": "Get a task list of the workflow.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "[Workflow]"
                ],
                "summary": "List Task",
                "operationId": "list-task",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID of the workflow.",
                        "name": "wfId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully get a task list.",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.Task"
                            }
                        }
                    },
                    "400": {
                        "description": "Sent bad request.",
                        "schema": {
                            "$ref": "#/definitions/common.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Failed to get a task list.",
                        "schema": {
                            "$ref": "#/definitions/common.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/workflow/{wfId}/task/{taskId}": {
            "get": {
                "description": "Get the task.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "[Workflow]"
                ],
                "summary": "Get Task",
                "operationId": "get-task",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID of the workflow.",
                        "name": "wfId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "ID of the task.",
                        "name": "taskId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully get the task.",
                        "schema": {
                            "$ref": "#/definitions/model.Task"
                        }
                    },
                    "400": {
                        "description": "Sent bad request.",
                        "schema": {
                            "$ref": "#/definitions/common.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Failed to get the task.",
                        "schema": {
                            "$ref": "#/definitions/common.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/workflow/{wfId}/task_group": {
            "get": {
                "description": "Get a task group list of the workflow.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "[Workflow]"
                ],
                "summary": "List TaskGroup",
                "operationId": "list-task-group",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID of the workflow.",
                        "name": "wfId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully get a task group list.",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.TaskGroup"
                            }
                        }
                    },
                    "400": {
                        "description": "Sent bad request.",
                        "schema": {
                            "$ref": "#/definitions/common.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Failed to get a task group list.",
                        "schema": {
                            "$ref": "#/definitions/common.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/workflow/{wfId}/task_group/{tgId}": {
            "get": {
                "description": "Get the task group.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "[Workflow]"
                ],
                "summary": "Get TaskGroup",
                "operationId": "get-task-group",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID of the workflow.",
                        "name": "wfId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "ID of the task group.",
                        "name": "tgId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully get the task group.",
                        "schema": {
                            "$ref": "#/definitions/model.Task"
                        }
                    },
                    "400": {
                        "description": "Sent bad request.",
                        "schema": {
                            "$ref": "#/definitions/common.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Failed to get the task group.",
                        "schema": {
                            "$ref": "#/definitions/common.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/workflow/{wfId}/task_group/{tgId}/task": {
            "get": {
                "description": "Get a task list from the task group.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "[Workflow]"
                ],
                "summary": "List Task from Task Group",
                "operationId": "list-task-from-task-group",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID of the workflow.",
                        "name": "wfId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "ID of the task group.",
                        "name": "tgId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully get a task list from the task group.",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.Task"
                            }
                        }
                    },
                    "400": {
                        "description": "Sent bad request.",
                        "schema": {
                            "$ref": "#/definitions/common.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Failed to get a task list from the task group.",
                        "schema": {
                            "$ref": "#/definitions/common.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/workflow/{wfId}/task_group/{tgId}/task/{taskId}": {
            "get": {
                "description": "Get the task from the task group.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "[Workflow]"
                ],
                "summary": "Get Task from Task Group",
                "operationId": "get-task-from-task-group",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID of the workflow.",
                        "name": "wfId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "ID of the task group.",
                        "name": "tgId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "ID of the task.",
                        "name": "taskId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully get the task from the task group.",
                        "schema": {
                            "$ref": "#/definitions/model.Task"
                        }
                    },
                    "400": {
                        "description": "Sent bad request.",
                        "schema": {
                            "$ref": "#/definitions/common.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Failed to get the task from the task group.",
                        "schema": {
                            "$ref": "#/definitions/common.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/workflow/{wfId}/version": {
            "get": {
                "description": "Get a workflowVersion list.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "[Workflow]"
                ],
                "summary": "List workflowVersion",
                "operationId": "list-workflowVersion",
                "parameters": [
                    {
                        "type": "string",
                        "description": "wfId of the workflow",
                        "name": "wfId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Page of the workflowVersion list.",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Row of the workflowVersion list.",
                        "name": "row",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully get a workflowVersion list.",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.WorkflowVersionSwg"
                            }
                        }
                    },
                    "400": {
                        "description": "Sent bad request.",
                        "schema": {
                            "$ref": "#/definitions/common.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Failed to get a workflowVersion list.",
                        "schema": {
                            "$ref": "#/definitions/common.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/workflow/{wfId}/versioned": {
            "put": {
                "description": "Workflow를 덮어쓰지 않고 새 WorkflowVersion을 생성한 뒤, 삭제분은 soft delete, 나머지는 upsert. Workflow = 현재 최신 정의 포인터, WorkflowVersion = 불변 스냅샷(append-only).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "[Workflow]"
                ],
                "summary": "Update Workflow (버전 생성)",
                "operationId": "update-workflow-versioned",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID of the workflow.",
                        "name": "wfId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Workflow to modify.",
                        "name": "Workflow",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.CreateWorkflowReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully update the workflow",
                        "schema": {
                            "$ref": "#/definitions/model.Workflow"
                        }
                    },
                    "400": {
                        "description": "Sent bad request.",
                        "schema": {
                            "$ref": "#/definitions/common.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Failed to update the workflow",
                        "schema": {
                            "$ref": "#/definitions/common.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/workflow/{wfId}/workflowRun/{wfRunId}/range": {
            "post": {
                "description": "Clear the task Instance.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "[Workflow]"
                ],
                "summary": "Clear taskInstances",
                "operationId": "clear-task-instances",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID of the workflow.",
                        "name": "wfId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "ID of the wfRunId.",
                        "name": "wfRunId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Workflow content",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.TaskClearOption"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully clear the taskInstances.",
                        "schema": {
                            "$ref": "#/definitions/model.TaskInstanceReference"
                        }
                    },
                    "400": {
                        "description": "Sent bad request.",
                        "schema": {
                            "$ref": "#/definitions/common.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Failed to clear the taskInstances.",
                        "schema": {
                            "$ref": "#/definitions/common.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/workflow/{wfId}/workflowRun/{wfRunId}/task/{taskId}/taskTryNum/{taskTryNum}/logs": {
            "get": {
                "description": "Get the task Logs.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "[Workflow]"
                ],
                "summary": "Get Task Logs",
                "operationId": "get-task-logs",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID of the workflow.",
                        "name": "wfId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "ID of the workflowRunId.",
                        "name": "wfRunId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "ID of the task.",
                        "name": "taskId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "ID of the taskTryNum.",
                        "name": "taskTryNum",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully get the task Logs.",
                        "schema": {
                            "$ref": "#/definitions/model.TaskLog"
                        }
                    },
                    "400": {
                        "description": "Sent bad request.",
                        "schema": {
                            "$ref": "#/definitions/common.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Failed to get the task Logs.",
                        "schema": {
                            "$ref": "#/definitions/common.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/workflow/{wfId}/workflowRun/{wfRunId}/task/{taskId}/taskTryNum/{taskTryNum}/logs/download": {
            "get": {
                "description": "Download the task logs as a file.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "[Workflow]"
                ],
                "summary": "Download Task Logs",
                "operationId": "get-task-logs-download",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID of the workflow.",
                        "name": "wfId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "ID of the workflowRunId.",
                        "name": "wfRunId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "ID of the task.",
                        "name": "taskId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "ID of the taskTryNum.",
                        "name": "taskTryNum",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Log file downloaded successfully.",
                        "schema": {
                            "type": "file"
                        }
                    },
                    "400": {
                        "description": "Sent bad request.",
                        "schema": {
                            "$ref": "#/definitions/common.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Failed to get the task Logs.",
                        "schema": {
                            "$ref": "#/definitions/common.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/workflow/{wfId}/workflowRun/{wfRunId}/taskInstances": {
            "get": {
                "description": "Get the task Logs.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "[Workflow]"
                ],
                "summary": "Get taskInstances",
                "operationId": "get-task-instances",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID of the workflow.",
                        "name": "wfId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "ID of the workflow.",
                        "name": "wfRunId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully get the taskInstances.",
                        "schema": {
                            "$ref": "#/definitions/model.TaskInstance"
                        }
                    },
                    "400": {
                        "description": "Sent bad request.",
                        "schema": {
                            "$ref": "#/definitions/common.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Failed to get the taskInstances.",
                        "schema": {
                            "$ref": "#/definitions/common.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/workflow_template": {
            "get": {
                "description": "Get a list of workflow template.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "[Workflow Template]"
                ],
                "summary": "List WorkflowTemplate",
                "operationId": "list-workflow-template",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Name of the workflow template",
                        "name": "name",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Page of the workflow template list.",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Row of the workflow template list.",
                        "name": "row",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully get a list of workflow template.",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.WorkflowTemplate"
                            }
                        }
                    },
                    "400": {
                        "description": "Sent bad request.",
                        "schema": {
                            "$ref": "#/definitions/common.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Failed to get a list of workflow template.",
                        "schema": {
                            "$ref": "#/definitions/common.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/workflow_template/name/{wfName}": {
            "get": {
                "description": "Get the workflow template by name.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "[Workflow Template]"
                ],
                "summary": "Get WorkflowTemplate by Name",
                "operationId": "get-workflow-template-by-name",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Name of the WorkflowTemplate",
                        "name": "wfName",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully get the workflow template",
                        "schema": {
                            "$ref": "#/definitions/model.WorkflowTemplate"
                        }
                    },
                    "400": {
                        "description": "Sent bad request.",
                        "schema": {
                            "$ref": "#/definitions/common.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Failed to get the workflow template",
                        "schema": {
                            "$ref": "#/definitions/common.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/workflow_template/{wftId}": {
            "get": {
                "description": "Get the workflow template.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "[Workflow Template]"
                ],
                "summary": "Get WorkflowTemplate",
                "operationId": "get-workflow-template",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID of the WorkflowTemplate",
                        "name": "wftId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully get the workflow template",
                        "schema": {
                            "$ref": "#/definitions/model.WorkflowTemplate"
                        }
                    },
                    "400": {
                        "description": "Sent bad request.",
                        "schema": {
                            "$ref": "#/definitions/common.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Failed to get the workflow template",
                        "schema": {
                            "$ref": "#/definitions/common.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "common.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        },
        "domain.ParameterStructure": {
            "type": "object",
            "properties": {
                "properties": {
                    "type": "object",
                    "additionalProperties": {
                        "$ref": "#/definitions/domain.PropertyDef"
                    }
                },
                "required": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "domain.PropertyDef": {
            "type": "object",
            "properties": {
                "default": {},
                "description": {
                    "type": "string"
                },
                "enum": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "example": {},
                "items": {
                    "$ref": "#/definitions/domain.PropertyDef"
                },
                "properties": {
                    "type": "object",
                    "additionalProperties": {
                        "$ref": "#/definitions/domain.PropertyDef"
                    }
                },
                "required": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "domain.TaskComponent": {
            "type": "object",
            "required": [
                "data",
                "id",
                "name"
            ],
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "data": {
                    "$ref": "#/definitions/domain.TaskComponentData"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "is_example": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "domain.TaskComponentData": {
            "type": "object",
            "properties": {
                "body_params": {
                    "$ref": "#/definitions/domain.ParameterStructure"
                },
                "options": {
                    "$ref": "#/definitions/domain.TaskComponentOptions"
                },
                "path_params": {
                    "$ref": "#/definitions/domain.ParameterStructure"
                },
                "query_params": {
                    "$ref": "#/definitions/domain.ParameterStructure"
                }
            }
        },
        "domain.TaskComponentOptions": {
            "type": "object",
            "properties": {
                "api_connection_id": {
                    "type": "string"
                },
                "endpoint": {
                    "type": "string"
                },
                "extra": {
                    "type": "object",
                    "additionalProperties": true
                },
                "method": {
                    "type": "string"
                },
                "request_body": {
                    "type": "string"
                }
            }
        },
        "model.CreateDataReq": {
            "type": "object",
            "required": [
                "task_groups"
            ],
            "properties": {
                "description": {
                    "type": "string"
                },
                "task_groups": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.CreateTaskGroupReq"
                    }
                }
            }
        },
        "model.CreateTaskComponentReq": {
            "type": "object",
            "required": [
                "data",
                "name"
            ],
            "properties": {
                "data": {
                    "$ref": "#/definitions/domain.TaskComponentData"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "model.CreateTaskGroupReq": {
            "type": "object",
            "required": [
                "name",
                "tasks"
            ],
            "properties": {
                "description": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "tasks": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.CreateTaskReq"
                    }
                }
            }
        },
        "model.CreateTaskReq": {
            "type": "object",
            "required": [
                "name",
                "request_body",
                "task_component"
            ],
            "properties": {
                "dependencies": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "extra": {
                    "type": "object",
                    "additionalProperties": true
                },
                "name": {
                    "type": "string"
                },
                "path_params": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "query_params": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "request_body": {
                    "type": "string"
                },
                "task_component": {
                    "type": "string"
                }
            }
        },
        "model.CreateWorkflowReq": {
            "type": "object",
            "required": [
                "data",
                "name"
            ],
            "properties": {
                "data": {
                    "$ref": "#/definitions/model.CreateDataReq"
                },
                "name": {
                    "type": "string"
                },
                "spec_version": {
                    "type": "string"
                }
            }
        },
        "model.CreateWorkflowRunReq": {
            "type": "object",
            "required": [
                "workflow_id",
                "workflow_run_id"
            ],
            "properties": {
                "end_date": {
                    "type": "string"
                },
                "execution_date": {
                    "type": "string"
                },
                "run_type": {
                    "type": "string"
                },
                "start_date": {
                    "type": "string"
                },
                "state": {
                    "type": "string"
                },
                "workflow_id": {
                    "type": "string"
                },
                "workflow_run_id": {
                    "type": "string"
                }
            }
        },
        "model.Data": {
            "type": "object",
            "required": [
                "task_groups"
            ],
            "properties": {
                "description": {
                    "type": "string"
                },
                "task_groups": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.TaskGroup"
                    }
                }
            }
        },
        "model.EventLog": {
            "type": "object",
            "properties": {
                "event": {
                    "type": "string"
                },
                "extra": {
                    "type": "string"
                },
                "run_id": {
                    "type": "string"
                },
                "task_id": {
                    "type": "string"
                },
                "task_name": {
                    "type": "string"
                },
                "when": {
                    "type": "string"
                },
                "workflow_id": {
                    "type": "string"
                },
                "workflow_run_id": {
                    "type": "string"
                }
            }
        },
        "model.ImportError": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        },
        "model.ImportErrorCollection": {
            "type": "object",
            "properties": {
                "import_errors": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.ImportError"
                    }
                },
                "total_entries": {
                    "type": "integer"
                }
            }
        },
        "model.RunScriptReq": {
            "type": "object",
            "properties": {
                "content": {
                    "description": "Base64 encoded script content.",
                    "type": "string"
                },
                "mci_id": {
                    "type": "string"
                },
                "ns_id": {
                    "type": "string"
                },
                "vm_id": {
                    "type": "string"
                }
            }
        },
        "model.ScriptResult": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                },
                "is_success": {
                    "type": "boolean"
                },
                "output": {
                    "type": "string"
                }
            }
        },
        "model.SimpleMsg": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        },
        "model.SleepTimeReq": {
            "type": "object",
            "properties": {
                "time": {
                    "description": "Ex: 300 = 300sec, 1m 30s = 1min 30seconds, 1h 10m 15s = 1hour 10minutes 15seconds, 1d 1s = 1day 1second, No Input Default: 10s",
                    "type": "string"
                }
            }
        },
        "model.Task": {
            "type": "object",
            "required": [
                "id",
                "name",
                "request_body",
                "task_component",
                "task_group_id",
                "workflow_id"
            ],
            "properties": {
                "dependencies": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "extra": {
                    "type": "object",
                    "additionalProperties": true
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "path_params": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "query_params": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "request_body": {
                    "type": "string"
                },
                "task_component": {
                    "type": "string"
                },
                "task_group_id": {
                    "type": "string"
                },
                "workflow_id": {
                    "type": "string"
                }
            }
        },
        "model.TaskClearOption": {
            "type": "object",
            "properties": {
                "dryRun": {
                    "type": "boolean"
                },
                "includeDownstream": {
                    "type": "boolean"
                },
                "includeUpstream": {
                    "description": "IncludeFuture     bool     ` + "`" + `json:\"includeFuture\"` + "`" + `\nIncludeParentdag  bool     ` + "`" + `json:\"includeParentdag\"` + "`" + `\nIncludePast       bool     ` + "`" + `json:\"includePast\"` + "`" + `\nIncludeSubdags    bool     ` + "`" + `json:\"includeSubdags\"` + "`" + `",
                    "type": "boolean"
                },
                "onlyFailed": {
                    "type": "boolean"
                },
                "onlyRunning": {
                    "type": "boolean"
                },
                "resetDagRuns": {
                    "type": "boolean"
                },
                "taskIds": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "model.TaskGroup": {
            "type": "object",
            "required": [
                "id",
                "name",
                "tasks",
                "workflow_id"
            ],
            "properties": {
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "tasks": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.Task"
                    }
                },
                "workflow_id": {
                    "type": "string"
                }
            }
        },
        "model.TaskInstance": {
            "type": "object",
            "properties": {
                "duration_date": {
                    "type": "number"
                },
                "end_date": {
                    "type": "string"
                },
                "execution_date": {
                    "type": "string"
                },
                "is_software_migration_task": {
                    "type": "boolean"
                },
                "software_migration_execution_id": {
                    "type": "string"
                },
                "start_date": {
                    "type": "string"
                },
                "state": {
                    "type": "string"
                },
                "task_id": {
                    "type": "string"
                },
                "task_name": {
                    "type": "string"
                },
                "try_number": {
                    "type": "integer"
                },
                "workflow_id": {
                    "type": "string"
                },
                "workflow_run_id": {
                    "type": "string"
                }
            }
        },
        "model.TaskInstanceReference": {
            "type": "object",
            "properties": {
                "execution_date": {
                    "type": "string"
                },
                "task_id": {
                    "description": "The task ID.",
                    "type": "string"
                },
                "task_name": {
                    "type": "string"
                },
                "workflow_id": {
                    "description": "The DAG ID.",
                    "type": "string"
                },
                "workflow_run_id": {
                    "description": "The DAG run ID.",
                    "type": "string"
                }
            }
        },
        "model.TaskLog": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string"
                }
            }
        },
        "model.Workflow": {
            "type": "object",
            "required": [
                "data",
                "id",
                "name",
                "spec_version"
            ],
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "data": {
                    "$ref": "#/definitions/model.Data"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "spec_version": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "model.WorkflowRun": {
            "type": "object",
            "properties": {
                "duration_date": {
                    "type": "number"
                },
                "end_date": {
                    "type": "string"
                },
                "execution_date": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "run_type": {
                    "type": "string"
                },
                "start_date": {
                    "type": "string"
                },
                "state": {
                    "type": "string"
                },
                "workflow_id": {
                    "type": "string"
                }
            }
        },
        "model.WorkflowStatus": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer"
                },
                "state": {
                    "type": "string"
                }
            }
        },
        "model.WorkflowTemplate": {
            "type": "object",
            "required": [
                "data",
                "name",
                "spec_version"
            ],
            "properties": {
                "data": {
                    "$ref": "#/definitions/model.Data"
                },
                "name": {
                    "type": "string"
                },
                "spec_version": {
                    "type": "string"
                }
            }
        },
        "model.WorkflowVersionSwg": {
            "type": "object",
            "required": [
                "id",
                "spec_version",
                "version",
                "workflow_id"
            ],
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "definition_snapshot": {
                    "type": "object",
                    "additionalProperties": true
                },
                "id": {
                    "type": "string"
                },
                "spec_version": {
                    "type": "string"
                },
                "version": {
                    "type": "integer"
                },
                "workflow_id": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "latest",
	Host:             "",
	BasePath:         "/cicada",
	Schemes:          []string{},
	Title:            "CM-Cicada REST API",
	Description:      "Workflow management module",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
